services:
  mysql:
    image: mysql:8.0
    container_name: nyc311-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass!
      MYSQL_DATABASE: nyc311
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Life8574!
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5510:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/001_create_database.sql:/docker-entrypoint-initdb.d/001_create_database.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass!"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: nyc311-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  mongo_data:
